### ISSUE TITLE
Use of deprecated getfuncargvalue

### ISSUE THREAD

**Issue by denisdubovitskiy** [smarie/python-pytest-steps#10]
Here is the warning: `steps_parametrizer.py:94: RemovedInPytest4Warning: getfuncargvalue is deprecated, use getfixturevalue`

Is it planned to be fixed?
Thanks

**Comment by smarie** [comment]
Nice catch, thanks ! Yes, we'll have to take care of this indeed. Probably not much of a problem if `getfixturevalue` provides the same functionality and exists in legacy pytest versions. Otherwise we'll have to test for existence and choose whichever is available.

If you feel like you can have a go do not hesitate to propose a PR. Otherwise I'll have a look in the upcoming days

**Comment by smarie** [comment]
I did it, will push it now

**Comment by denisdubovitskiy** [comment]
Thank you! I was on the verge of making a PR, but unfortunately I didn't have time for it

**Comment by smarie** [comment]
ah sorry I should have waited slightly more.. this should now be fixed (in 1.0.1 that is being currently built by travis)
