### ISSUE TITLE
Travis CI gets stuck on forked repo

### ISSUE THREAD

**Issue by r4lv** [smarie/python-pytest-steps#3]
Dear Sylvain,

I forked python-pytest-steps and started a Travis CI build. However, the CI gets stuck at the `after_success` step, waiting for:

``` text
Enter passphrase for ci_tools/github_travis_rsa: 
```

(please have a look at the full logs on https://travis-ci.com/r4lv/python-pytest-steps)

Maybe the deployment step could be deactivated for forked repos by testing the GitHub URL in the `.travis.yml`?

**Comment by smarie** [comment]
Good catch.
I think that f4d88477b7e5d6d480bcb547b4e1fb81ab698d3a solved it, could you check ?

**Comment by r4lv** [comment]
Sadly no... The call to `openssl` always creates the (empty) `ci_tools/github_travis_rsa` file, even if `iv undefined`. So the `if -f` test is always true.

Here is my log:
https://travis-ci.com/r4lv/python-pytest-steps/jobs/137921657#L986

Maybe you could use
``` bash
if [ -z "$encrypted_ddaf3af99ed9_key" ]; then
```
instead, as I assume you are setting that environment variable on the Travis CI web interface?

**Comment by smarie** [comment]
Ok then, I replaced it with

```bash
if [ -s "ci_tools/github_travis_rsa" ]
```

Let me know if that's better.

I use the travis cli tool to generate this environment variable to share my secret (the ssl key) without committing it in the sources. Since the variable name is generated by travis I prefer to have it in a single line (in particular because for every new repo I do the process, travis CLI prints that line and I copy/paste it in travis.yml - so I prefer to avoid stupid mistakes where I forget to paste it in a second place).

**Comment by r4lv** [comment]
Sorry for the late answer. Now the CI works as expected, nice!

**Comment by smarie** [comment]
Thanks a lot for the feedback!
